//------------------------------------------------------------------------------
// <auto-generated>
//     This file is a hand-written wrapper around an auto-generated
//     PublicResXFileCodeGenerator output. The generator is not always available
//     on the build host (CI uses windows-latest where the add-in is installed,
//     but local dev environments may lack it), so this wrapper provides a
//     stable string-based accessor that resolves keys via ResourceManager with
//     en fallback.
//
//     The resource set is split per section (Strings.{Section}.resx +
//     Strings.{Section}.{locale}.resx). Common keys live in Strings.Common;
//     feature-specific keys live in their view's section file. This facade
//     threads through the section managers in priority order and returns the
//     first match (current UI culture, then invariant) so existing call sites
//     remain unchanged.
//
//     To migrate to generator-produced code, replace the contents of this file
//     with the auto-generated <name>.<PropertyName> accessors and keep the
//     same property name + type signature.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastileDesktop.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Strongly-typed entry point for the Tastile Desktop resource strings.
/// Resolves the named key against the current UICulture in each per-section
/// ResourceManager, falling back to the neutral (en) resource, then to the
/// invariant culture, then to "" if the key is missing entirely.
/// </summary>
internal static class Strings
{
    // Ordered by specificity — common first, then feature sections. The lookup
    // returns the first match across all managers, so a key that exists in
    // more than one section resource will be returned from the earliest one
    // in this list. Section files are kept mutually exclusive (no key overlap).
    //
    // Tiered base names: TastileDesktop.Resources.<Category>.Strings.<Section>
    // where Category is App/, Features/, or System/ (Marketing/ is omitted on
    // desktop because no marketing resx files exist).
    private static readonly ResourceManager[] _managers =
    {
        new ResourceManager("TastileDesktop.Resources.App.Strings.Common", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.App.Strings.Shell", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Auth", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Dashboard", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Timeline", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Tiles", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Tasks", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Calendar", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Schedule", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.Projects", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Execution", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Prompt", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Notifications", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Settings", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Preferences", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Account", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.Features.Strings.QuickCreate", typeof(Strings).Assembly),
        new ResourceManager("TastileDesktop.Resources.System.Strings.Integrations", typeof(Strings).Assembly),
    };

    /// <summary>
    /// Looks up a resource string by name. Returns the value for the
    /// current UI culture from the first section manager that defines it,
    /// falling back to the invariant culture, then to an empty string if
    /// the key is not present in any satellite assembly.
    /// </summary>
    public static string Get(string name)
    {
        if (string.IsNullOrEmpty(name)) return string.Empty;
        foreach (var rm in _managers)
        {
            var value = rm.GetString(name, CultureInfo.CurrentUICulture);
            if (value is not null) return value;
            value = rm.GetString(name, CultureInfo.InvariantCulture);
            if (value is not null) return value;
        }
        return string.Empty;
    }
}
