// <auto-generated />
// This file is a stable, SDK-independent source of `global using Xunit;`.
// The csproj declares <Using Include="Xunit" /> which most SDKs convert to
// a generated GlobalUsings.g.cs entry, but the conversion is not guaranteed
// across SDK versions. Adding `global using Xunit;` directly here means the
// directive is emitted regardless of SDK behavior. This keeps every test
// file in the project compiling with [Fact] / [Theory] attributes even when
// the SDK is older than the one used locally.
global using Xunit;
