// <auto-generated />
// This file is a stable, SDK-independent source of `global using Xunit;`.
// The project formerly declared <Using Include="Xunit" />, which most SDKs
// convert to a generated GlobalUsings.g.cs entry. That conversion was not
// reliable across SDK versions, so `global using Xunit;` now lives here and
// directive is emitted regardless of SDK behavior. This keeps every test
// file in the project compiling with [Fact] / [Theory] attributes even when
// the SDK is older than the one used locally.
global using Xunit;
