# Translation map for the 3 new desktop languages.
# Keys are the resx resource names; values are the per-language strings.
# Translations are kept consistent with the web (tastile-web) and android
# (tastile-android) quickcreate copy where they exist, and otherwise
# translated literally to keep parity across platforms.

$translations = [ordered]@{
    'de' = @{
        'CreateTile.CreateError'             = 'Erstellungsfehler'
        'CreateTile.CreateFailed'            = 'Kachel konnte nicht erstellt werden.'
        'CreateTile.CreateFailedWithMessage' = 'Kachel konnte nicht erstellt werden: {0}'
        'CreateTile.DeleteFailed'            = 'Kachel konnte nicht gelöscht werden.'
        'CreateTile.EditHeading'             = 'Kachel bearbeiten'
        'CreateTile.EditTitle'               = 'Kachel bearbeiten'
        'CreateTile.ErrorPrefix'             = 'Fehler: {0}'
        'CreateTile.NoResponse'              = 'Daemon hat nicht geantwortet.'
        'CreateTile.ProjectCreateNew'        = '„{0}“ erstellen'
        'CreateTile.QuotaCheckException'     = 'Kachel-Limit konnte nicht geprüft werden: {0}'
        'CreateTile.QuotaCheckFailed'        = 'Kachel-Limit konnte nicht überprüft werden.'
        'CreateTile.QuotaLimitReached'       = 'Limit des kostenlosen Tarifs erreicht (100 Kacheln). Bitte Kacheln archivieren oder Tarif upgraden.'
        'CreateTile.SubmitBlockedHint'       = 'Behebe den markierten Fehler, um fortzufahren.'
        'CreateTile.SubmitFailedRetry'       = 'Übermittlung fehlgeschlagen. Bitte erneut versuchen.'
        'CreateTile.TagCreateNew'            = 'Neues Tag hinzufügen: #{0}'
        'CreateTile.Title'                   = 'Kachel erstellen'
        'CreateTile.TitleRequired'           = 'Titel ist erforderlich.'
        'CreateTile.UpdateError'             = 'Aktualisierungsfehler'
        'CreateTile.UpdateFailed'            = 'Kachel konnte nicht aktualisiert werden.'
        'CreateTile.UpdateFailedWithMessage' = 'Kachel konnte nicht aktualisiert werden: {0}'
        'CreateTile.ValidationDurationRequired'         = 'Dauer ist erforderlich, wenn Start oder Ende angegeben ist.'
        'CreateTile.ValidationRecurrenceEndAfterStart'   = 'Endzeit der Wiederholung muss nach der Startzeit liegen.'
        'CreateTile.ValidationRecurrenceIntervalMin'     = 'Wiederholungsintervall muss mindestens 1 sein.'
        'CreateTile.ValidationStartEndOrder'             = 'Reihenfolge von Start und Ende prüfen.'
        'CreateTile.ValidationTitleRequired'             = 'Titel eingeben.'
        'CreateTile.AllDay'                              = 'Ganztägig'
        'CreateTile.CancelButton'                        = 'Abbrechen'
        'CreateTile.ColorLabel'                          = 'Farbe'
        'CreateTile.CompletionModeLabel'                 = 'Abschlussmodus'
        'CreateTile.CompletionModeNormal'                = 'Normal'
        'CreateTile.CompletionModeRecurring'             = 'Wiederholt'
        'CreateTile.DeleteButton'                        = 'Löschen'
        'CreateTile.DetailsDetailedTitle'               = 'Erweiterte Optionen'
        'CreateTile.DetailsEventTitle'                   = 'Termin­details'
        'CreateTile.DetailsRecurringTitle'               = 'Wiederholungs­details'
        'CreateTile.DetailsTaskTitle'                    = 'Aufgaben­details'
        'CreateTile.DueDatePlaceholder'                  = 'Datum (optional)'
        'CreateTile.DueTimeLabel'                        = 'Fälligkeits­zeit'
        'CreateTile.DurationCustom'                      = 'Benutzerdefiniert…'
        'CreateTile.DurationLabel'                       = 'Dauer'
        'CreateTile.DurationManual'                      = 'Minuten eingeben'
        'CreateTile.EditPrimaryButton'                   = 'Speichern'
        'CreateTile.EndButton'                           = 'Ende'
        'CreateTile.EndDate'                             = 'Enddatum'
        'CreateTile.EndTimeLabel'                        = 'Endzeit'
        'CreateTile.FrequencyDaily'                      = 'Täglich'
        'CreateTile.FrequencyMonthly'                    = 'Monatlich'
        'CreateTile.FrequencyWeekly'                     = 'Wöchentlich'
        'CreateTile.Heading'                             = 'Kachel erstellen'
        'CreateTile.HoursLabel'                          = 'Stunden'
        'CreateTile.IntervalUnitDay'                     = 'Tag'
        'CreateTile.IntervalUnitHour'                    = 'Std.'
        'CreateTile.IntervalUnitMin'                     = 'Min.'
        'CreateTile.IntervalValueLabel'                  = 'Alle'
        'CreateTile.KindLabel'                           = 'Typ'
        'CreateTile.KindLabelTile'                       = 'Label'
        'CreateTile.KindTask'                            = 'Aufgabe'
        'CreateTile.MaximizeButton'                      = 'Im Zeitfenster maximieren'
        'CreateTile.MemoLabel'                           = 'Notiz'
        'CreateTile.MemoPlaceholder'                     = 'Ergänzende Notizen'
        'CreateTile.MinutesLabel'                        = 'Minuten'
        'CreateTile.MonthlyByDay'                        = 'Nach Tag'
        'CreateTile.MonthlyByWeekday'                    = 'Nach Wochentag'
        'CreateTile.MonthlyDayOfMonthLabel'              = 'Tag des Monats'
        'CreateTile.MonthlyLastWeek'                      = 'Letzte'
        'CreateTile.MonthlyWeek'                         = 'Welche Woche'
        'CreateTile.MonthlyWeekday'                      = 'Wochentag'
        'CreateTile.MonthlyWeekFirst'                    = '1.'
        'CreateTile.MonthlyWeekFourth'                   = '4.'
        'CreateTile.MonthlyWeekOfMonthLabel'             = 'Woche des Monats'
        'CreateTile.MonthlyWeekSecond'                   = '2.'
        'CreateTile.MonthlyWeekThird'                    = '3.'
        'CreateTile.PrimaryButton'                       = 'Erstellen'
        'CreateTile.ProjectLabel'                        = 'Projekt'
        'CreateTile.ProjectPlaceholder'                  = 'Projektname'
        'CreateTile.RecurrenceEndTime'                   = 'Endzeit'
        'CreateTile.RecurrencePrefix'                    = 'Alle'
        'CreateTile.RecurrenceStartTime'                 = 'Startzeit'
        'CreateTile.RecurrenceSuffixDaily'               = 'Tag(e)'
        'CreateTile.RecurrenceSuffixMonthly'             = 'Monat(e)'
        'CreateTile.RecurrenceSuffixWeekly'              = 'Woche(n)'
        'CreateTile.RecurrenceValidFrom'                 = 'Gültig ab'
        'CreateTile.RecurrenceValidityLabel'             = 'Gültigkeitszeitraum'
        'CreateTile.RecurrenceValidTo'                   = 'Gültig bis'
        'CreateTile.RepeatEndLabel'                      = 'Wiederholen bis'
        'CreateTile.RepeatModeDaily'                     = 'Täglich'
        'CreateTile.RepeatModeInterval'                  = 'Intervall'
        'CreateTile.RepeatModeMonthly'                   = 'Monatlich'
        'CreateTile.RepeatModeOnce'                      = 'Keine Wiederholung'
        'CreateTile.RepeatModeWeekly'                    = 'Wöchentlich'
        'CreateTile.SchedulableWindowEndLabel'           = 'Spätester Zeitpunkt'
        'CreateTile.SchedulableWindowStartLabel'         = 'Frühester Zeitpunkt'
        'CreateTile.SplitAllow'                          = 'Aufteilen erlauben'
        'CreateTile.SplitKeep'                           = 'Nicht aufteilen'
        'CreateTile.SplitLabel'                          = 'Aufteilung'
        'CreateTile.StartButton'                         = 'Start'
        'CreateTile.StartDate'                           = 'Startdatum'
        'CreateTile.StartTimeLabel'                      = 'Startzeit'
        'CreateTile.SubtasksAdd'                         = 'Teilaufgabe hinzufügen'
        'CreateTile.SubtasksEmpty'                       = 'Keine Teilaufgaben'
        'CreateTile.SubtasksLabel'                       = 'Teilaufgaben'
        'CreateTile.TagLabel'                            = 'Tags'
        'CreateTile.TagPlaceholder'                      = 'Tag-Name'
        'CreateTile.TimeModelDurationOnly'               = 'Nur Dauer'
        'CreateTile.TimeModelDurationOnlyHint'          = 'Keine feste Zeit — nur Dauer'
        'CreateTile.TimeModelFixedWindow'                = 'Festes Zeitfenster'
        'CreateTile.TimeModelWindowWithDuration'         = 'Zeitfenster + Dauer'
        'CreateTile.TimeOfDayLabel'                      = 'Tageszeit'
        'CreateTile.TimingLabel'                         = 'Ausführungs­zeitpunkt'
        'CreateTile.TitleLabel'                          = 'Titel'
        'CreateTile.TitlePlaceholder'                    = 'Titel hinzufügen'
        'CreateTile.WeekdayFri'                          = 'Fr'
        'CreateTile.WeekdayMon'                          = 'Mo'
        'CreateTile.WeekdaySat'                          = 'Sa'
        'CreateTile.WeekdaySun'                          = 'So'
        'CreateTile.WeekdayThu'                          = 'Do'
        'CreateTile.WeekdayTue'                          = 'Di'
        'CreateTile.WeekdayWed'                          = 'Mi'
        'CreateTile.WorkflowDetailed'                    = 'Erweitert'
        'CreateTile.WorkflowDetailedDescription'         = 'Alle Felder direkt bearbeiten'
        'CreateTile.WorkflowEvent'                       = 'Termin'
        'CreateTile.WorkflowEventDescription'            = 'Zeitblock im Kalender'
        'CreateTile.WorkflowRecurring'                   = 'Wiederholt'
        'CreateTile.WorkflowRecurringDescription'        = 'Sich regelmäßig wiederholend'
        'CreateTile.WorkflowTask'                        = 'Aufgabe'
        'CreateTile.WorkflowTaskDescription'             = 'Arbeit mit Zieldauer'
    }
    'fr' = @{
        'CreateTile.CreateError'             = 'Erreur de creation'
        'CreateTile.CreateFailed'            = 'Echec de la creation de la tuile.'
        'CreateTile.CreateFailedWithMessage' = 'Echec de la creation de la tuile : {0}'
        'CreateTile.DeleteFailed'            = 'Echec de la suppression de la tuile.'
        'CreateTile.EditHeading'             = 'Modifier la tuile'
        'CreateTile.EditTitle'               = 'Modifier la tuile'
        'CreateTile.ErrorPrefix'             = 'Erreur : {0}'
        'CreateTile.NoResponse'              = 'Le demon n''a pas repondu.'
        'CreateTile.ProjectCreateNew'        = 'Creer "{0}"'
        'CreateTile.QuotaCheckException'     = 'Impossible de verifier la limite de tuiles : {0}'
        'CreateTile.QuotaCheckFailed'        = 'Impossible de verifier la limite de tuiles.'
        'CreateTile.QuotaLimitReached'       = 'Limite du forfait gratuit atteinte (100 tuiles). Archivez des tuiles ou passez a un forfait superieur.'
        'CreateTile.SubmitBlockedHint'       = 'Corrigez l''erreur surlignee pour continuer.'
        'CreateTile.SubmitFailedRetry'       = 'L''envoi a echoue. Reessayez.'
        'CreateTile.TagCreateNew'            = 'Ajouter une etiquette #{0}'
        'CreateTile.Title'                   = 'Creer une tuile'
        'CreateTile.TitleRequired'           = 'Le titre est obligatoire.'
        'CreateTile.UpdateError'             = 'Erreur de mise a jour'
        'CreateTile.UpdateFailed'            = 'Echec de la mise a jour de la tuile.'
        'CreateTile.UpdateFailedWithMessage' = 'Echec de la mise a jour de la tuile : {0}'
        'CreateTile.ValidationDurationRequired'         = 'La duree est requise lorsqu''une heure de debut ou de fin est precisee.'
        'CreateTile.ValidationRecurrenceEndAfterStart'   = 'L''heure de fin de la recurrence doit etre posterieure a l''heure de debut.'
        'CreateTile.ValidationRecurrenceIntervalMin'     = 'L''intervalle de recurrence doit etre au moins 1.'
        'CreateTile.ValidationStartEndOrder'             = 'Verifiez l''ordre du debut et de la fin.'
        'CreateTile.ValidationTitleRequired'             = 'Saisissez un titre.'
        'CreateTile.AllDay'                              = 'Toute la journee'
        'CreateTile.CancelButton'                        = 'Annuler'
        'CreateTile.ColorLabel'                          = 'Couleur'
        'CreateTile.CompletionModeLabel'                 = 'Mode d''achevement'
        'CreateTile.CompletionModeNormal'                = 'Normal'
        'CreateTile.CompletionModeRecurring'             = 'Recurrent'
        'CreateTile.DeleteButton'                        = 'Supprimer'
        'CreateTile.DetailsDetailedTitle'                = 'Options detaillees'
        'CreateTile.DetailsEventTitle'                   = 'Details de l''evenement'
        'CreateTile.DetailsRecurringTitle'               = 'Details de la recurrence'
        'CreateTile.DetailsTaskTitle'                    = 'Details de la tache'
        'CreateTile.DueDatePlaceholder'                  = 'Date (facultatif)'
        'CreateTile.DueTimeLabel'                        = 'Heure d''echeance'
        'CreateTile.DurationCustom'                      = 'Personnalise...'
        'CreateTile.DurationLabel'                       = 'Duree'
        'CreateTile.DurationManual'                      = 'Minutes personnalisees'
        'CreateTile.EditPrimaryButton'                   = 'Enregistrer'
        'CreateTile.EndButton'                           = 'Fin'
        'CreateTile.EndDate'                             = 'Date de fin'
        'CreateTile.EndTimeLabel'                        = 'Heure de fin'
        'CreateTile.FrequencyDaily'                      = 'Quotidien'
        'CreateTile.FrequencyMonthly'                    = 'Mensuel'
        'CreateTile.FrequencyWeekly'                     = 'Hebdomadaire'
        'CreateTile.Heading'                             = 'Creer une tuile'
        'CreateTile.HoursLabel'                          = 'Heures'
        'CreateTile.IntervalUnitDay'                     = 'jour'
        'CreateTile.IntervalUnitHour'                    = 'h'
        'CreateTile.IntervalUnitMin'                     = 'min'
        'CreateTile.IntervalValueLabel'                  = 'Toutes les'
        'CreateTile.KindLabel'                           = 'Type'
        'CreateTile.KindLabelTile'                       = 'Etiquette'
        'CreateTile.KindTask'                            = 'Tache'
        'CreateTile.MaximizeButton'                      = 'Maximiser dans l''intervalle'
        'CreateTile.MemoLabel'                           = 'Memo'
        'CreateTile.MemoPlaceholder'                     = 'Notes complementaires'
        'CreateTile.MinutesLabel'                        = 'Minutes'
        'CreateTile.MonthlyByDay'                        = 'Par jour'
        'CreateTile.MonthlyByWeekday'                    = 'Par jour de la semaine'
        'CreateTile.MonthlyDayOfMonthLabel'              = 'Jour du mois'
        'CreateTile.MonthlyLastWeek'                      = 'Derniere'
        'CreateTile.MonthlyWeek'                         = 'Quelle semaine'
        'CreateTile.MonthlyWeekday'                      = 'Jour de la semaine'
        'CreateTile.MonthlyWeekFirst'                    = '1re'
        'CreateTile.MonthlyWeekFourth'                   = '4e'
        'CreateTile.MonthlyWeekOfMonthLabel'             = 'Semaine du mois'
        'CreateTile.MonthlyWeekSecond'                   = '2e'
        'CreateTile.MonthlyWeekThird'                    = '3e'
        'CreateTile.PrimaryButton'                       = 'Creer'
        'CreateTile.ProjectLabel'                        = 'Projet'
        'CreateTile.ProjectPlaceholder'                  = 'Nom du projet'
        'CreateTile.RecurrenceEndTime'                   = 'Heure de fin'
        'CreateTile.RecurrencePrefix'                    = 'Toutes les'
        'CreateTile.RecurrenceStartTime'                 = 'Heure de debut'
        'CreateTile.RecurrenceSuffixDaily'               = 'jour(s)'
        'CreateTile.RecurrenceSuffixMonthly'             = 'mois'
        'CreateTile.RecurrenceSuffixWeekly'              = 'semaine(s)'
        'CreateTile.RecurrenceValidFrom'                 = 'Valide a partir du'
        'CreateTile.RecurrenceValidityLabel'             = 'Periode de validite'
        'CreateTile.RecurrenceValidTo'                   = 'Valide jusqu''au'
        'CreateTile.RepeatEndLabel'                      = 'Repeter jusqu''a'
        'CreateTile.RepeatModeDaily'                     = 'Quotidien'
        'CreateTile.RepeatModeInterval'                  = 'Intervalle'
        'CreateTile.RepeatModeMonthly'                   = 'Mensuel'
        'CreateTile.RepeatModeOnce'                      = 'Ne pas repeter'
        'CreateTile.RepeatModeWeekly'                    = 'Hebdomadaire'
        'CreateTile.SchedulableWindowEndLabel'           = 'Heure la plus tardive'
        'CreateTile.SchedulableWindowStartLabel'         = 'Heure la plus precoce'
        'CreateTile.SplitAllow'                          = 'Autoriser le fractionnement'
        'CreateTile.SplitKeep'                           = 'Ne pas fractionner'
        'CreateTile.SplitLabel'                          = 'Fractionnement'
        'CreateTile.StartButton'                         = 'Debut'
        'CreateTile.StartDate'                           = 'Date de debut'
        'CreateTile.StartTimeLabel'                      = 'Heure de debut'
        'CreateTile.SubtasksAdd'                         = 'Ajouter une sous-tache'
        'CreateTile.SubtasksEmpty'                       = 'Aucune sous-tache'
        'CreateTile.SubtasksLabel'                       = 'Sous-taches'
        'CreateTile.TagLabel'                            = 'Etiquettes'
        'CreateTile.TagPlaceholder'                      = 'Nom de l''etiquette'
        'CreateTile.TimeModelDurationOnly'               = 'Duree uniquement'
        'CreateTile.TimeModelDurationOnlyHint'          = 'Pas d''heure fixe - duree uniquement'
        'CreateTile.TimeModelFixedWindow'                = 'Fenetre fixe'
        'CreateTile.TimeModelWindowWithDuration'         = 'Fenetre + duree'
        'CreateTile.TimeOfDayLabel'                      = 'Heure de la journee'
        'CreateTile.TimingLabel'                         = 'Heure d''execution'
        'CreateTile.TitleLabel'                          = 'Titre'
        'CreateTile.TitlePlaceholder'                    = 'Ajouter un titre'
        'CreateTile.WeekdayFri'                          = 'Ven'
        'CreateTile.WeekdayMon'                          = 'Lun'
        'CreateTile.WeekdaySat'                          = 'Sam'
        'CreateTile.WeekdaySun'                          = 'Dim'
        'CreateTile.WeekdayThu'                          = 'Jeu'
        'CreateTile.WeekdayTue'                          = 'Mar'
        'CreateTile.WeekdayWed'                          = 'Mer'
        'CreateTile.WorkflowDetailed'                    = 'Detaille'
        'CreateTile.WorkflowDetailedDescription'         = 'Modifier chaque champ directement'
        'CreateTile.WorkflowEvent'                       = 'Evenement'
        'CreateTile.WorkflowEventDescription'            = 'Bloc de temps dans le calendrier'
        'CreateTile.WorkflowRecurring'                   = 'Recurrent'
        'CreateTile.WorkflowRecurringDescription'        = 'Repetition selon un planning'
        'CreateTile.WorkflowTask'                        = 'Tache'
        'CreateTile.WorkflowTaskDescription'             = 'Travail avec une duree cible'
    }
    'pt-BR' = @{
        'CreateTile.CreateError'             = 'Erro ao criar'
        'CreateTile.CreateFailed'            = 'Falha ao criar o bloco.'
        'CreateTile.CreateFailedWithMessage' = 'Falha ao criar o bloco: {0}'
        'CreateTile.DeleteFailed'            = 'Falha ao excluir o bloco.'
        'CreateTile.EditHeading'             = 'Editar bloco'
        'CreateTile.EditTitle'               = 'Editar bloco'
        'CreateTile.ErrorPrefix'             = 'Erro: {0}'
        'CreateTile.NoResponse'              = 'O daemon não respondeu.'
        'CreateTile.ProjectCreateNew'        = 'Criar "{0}"'
        'CreateTile.QuotaCheckException'     = 'Falha ao validar o limite de blocos: {0}'
        'CreateTile.QuotaCheckFailed'        = 'Não foi possível verificar o limite de blocos.'
        'CreateTile.QuotaLimitReached'       = 'Limite do plano gratuito atingido (100 blocos). Arquive blocos ou faça upgrade do plano.'
        'CreateTile.SubmitBlockedHint'       = 'Resolva o erro destacado para continuar.'
        'CreateTile.SubmitFailedRetry'       = 'Falha no envio. Tente novamente.'
        'CreateTile.TagCreateNew'            = 'Adicionar nova tag #{0}'
        'CreateTile.Title'                   = 'Criar bloco'
        'CreateTile.TitleRequired'           = 'O título é obrigatório.'
        'CreateTile.UpdateError'             = 'Erro ao atualizar'
        'CreateTile.UpdateFailed'            = 'Falha ao atualizar o bloco.'
        'CreateTile.UpdateFailedWithMessage' = 'Falha ao atualizar o bloco: {0}'
        'CreateTile.ValidationDurationRequired'         = 'A duração é obrigatória quando o início ou o fim é especificado.'
        'CreateTile.ValidationRecurrenceEndAfterStart'   = 'O horário final da recorrência deve ser depois do horário inicial.'
        'CreateTile.ValidationRecurrenceIntervalMin'     = 'O intervalo de recorrência deve ser de pelo menos 1.'
        'CreateTile.ValidationStartEndOrder'             = 'Verifique a ordem do início e do fim.'
        'CreateTile.ValidationTitleRequired'             = 'Digite um título.'
        'CreateTile.AllDay'                              = 'Dia inteiro'
        'CreateTile.CancelButton'                        = 'Cancelar'
        'CreateTile.ColorLabel'                          = 'Cor'
        'CreateTile.CompletionModeLabel'                 = 'Modo de conclusão'
        'CreateTile.CompletionModeNormal'                = 'Normal'
        'CreateTile.CompletionModeRecurring'             = 'Recorrente'
        'CreateTile.DeleteButton'                        = 'Excluir'
        'CreateTile.DetailsDetailedTitle'                = 'Opções detalhadas'
        'CreateTile.DetailsEventTitle'                   = 'Detalhes do evento'
        'CreateTile.DetailsRecurringTitle'               = 'Detalhes da recorrência'
        'CreateTile.DetailsTaskTitle'                    = 'Detalhes da tarefa'
        'CreateTile.DueDatePlaceholder'                  = 'Data (opcional)'
        'CreateTile.DueTimeLabel'                        = 'Horário de vencimento'
        'CreateTile.DurationCustom'                      = 'Personalizado…'
        'CreateTile.DurationLabel'                       = 'Duração'
        'CreateTile.DurationManual'                      = 'Minutos personalizados'
        'CreateTile.EditPrimaryButton'                   = 'Salvar'
        'CreateTile.EndButton'                           = 'Fim'
        'CreateTile.EndDate'                             = 'Data de término'
        'CreateTile.EndTimeLabel'                        = 'Horário de término'
        'CreateTile.FrequencyDaily'                      = 'Diário'
        'CreateTile.FrequencyMonthly'                    = 'Mensal'
        'CreateTile.FrequencyWeekly'                     = 'Semanal'
        'CreateTile.Heading'                             = 'Criar bloco'
        'CreateTile.HoursLabel'                          = 'Horas'
        'CreateTile.IntervalUnitDay'                     = 'dia'
        'CreateTile.IntervalUnitHour'                    = 'h'
        'CreateTile.IntervalUnitMin'                     = 'min'
        'CreateTile.IntervalValueLabel'                  = 'A cada'
        'CreateTile.KindLabel'                           = 'Tipo'
        'CreateTile.KindLabelTile'                       = 'Rótulo'
        'CreateTile.KindTask'                            = 'Tarefa'
        'CreateTile.MaximizeButton'                      = 'Maximizar dentro do intervalo'
        'CreateTile.MemoLabel'                           = 'Memo'
        'CreateTile.MemoPlaceholder'                     = 'Notas complementares'
        'CreateTile.MinutesLabel'                        = 'Minutos'
        'CreateTile.MonthlyByDay'                        = 'Por dia'
        'CreateTile.MonthlyByWeekday'                    = 'Por dia da semana'
        'CreateTile.MonthlyDayOfMonthLabel'              = 'Dia do mês'
        'CreateTile.MonthlyLastWeek'                      = 'Última'
        'CreateTile.MonthlyWeek'                         = 'Qual semana'
        'CreateTile.MonthlyWeekday'                      = 'Dia da semana'
        'CreateTile.MonthlyWeekFirst'                    = '1ª'
        'CreateTile.MonthlyWeekFourth'                   = '4ª'
        'CreateTile.MonthlyWeekOfMonthLabel'             = 'Semana do mês'
        'CreateTile.MonthlyWeekSecond'                   = '2ª'
        'CreateTile.MonthlyWeekThird'                    = '3ª'
        'CreateTile.PrimaryButton'                       = 'Criar'
        'CreateTile.ProjectLabel'                        = 'Projeto'
        'CreateTile.ProjectPlaceholder'                  = 'Nome do projeto'
        'CreateTile.RecurrenceEndTime'                   = 'Horário de término'
        'CreateTile.RecurrencePrefix'                    = 'A cada'
        'CreateTile.RecurrenceStartTime'                 = 'Horário de início'
        'CreateTile.RecurrenceSuffixDaily'               = 'dia(s)'
        'CreateTile.RecurrenceSuffixMonthly'             = 'mês(es)'
        'CreateTile.RecurrenceSuffixWeekly'              = 'semana(s)'
        'CreateTile.RecurrenceValidFrom'                 = 'Válido a partir de'
        'CreateTile.RecurrenceValidityLabel'             = 'Período de validade'
        'CreateTile.RecurrenceValidTo'                   = 'Válido até'
        'CreateTile.RepeatEndLabel'                      = 'Repetir até'
        'CreateTile.RepeatModeDaily'                     = 'Diário'
        'CreateTile.RepeatModeInterval'                  = 'Intervalo'
        'CreateTile.RepeatModeMonthly'                   = 'Mensal'
        'CreateTile.RepeatModeOnce'                      = 'Não repetir'
        'CreateTile.RepeatModeWeekly'                    = 'Semanal'
        'CreateTile.SchedulableWindowEndLabel'           = 'Horário mais tardio'
        'CreateTile.SchedulableWindowStartLabel'         = 'Horário mais cedo'
        'CreateTile.SplitAllow'                          = 'Permitir divisão'
        'CreateTile.SplitKeep'                           = 'Não dividir'
        'CreateTile.SplitLabel'                          = 'Divisão'
        'CreateTile.StartButton'                         = 'Início'
        'CreateTile.StartDate'                           = 'Data de início'
        'CreateTile.StartTimeLabel'                      = 'Horário de início'
        'CreateTile.SubtasksAdd'                         = 'Adicionar subtarefa'
        'CreateTile.SubtasksEmpty'                       = 'Nenhuma subtarefa'
        'CreateTile.SubtasksLabel'                       = 'Subtarefas'
        'CreateTile.TagLabel'                            = 'Tags'
        'CreateTile.TagPlaceholder'                      = 'Nome da tag'
        'CreateTile.TimeModelDurationOnly'               = 'Apenas duração'
        'CreateTile.TimeModelDurationOnlyHint'          = 'Sem horário fixo — apenas duração'
        'CreateTile.TimeModelFixedWindow'                = 'Janela fixa'
        'CreateTile.TimeModelWindowWithDuration'         = 'Janela + duração'
        'CreateTile.TimeOfDayLabel'                      = 'Horário do dia'
        'CreateTile.TimingLabel'                         = 'Horário de execução'
        'CreateTile.TitleLabel'                          = 'Título'
        'CreateTile.TitlePlaceholder'                    = 'Adicionar título'
        'CreateTile.WeekdayFri'                          = 'Sex'
        'CreateTile.WeekdayMon'                          = 'Seg'
        'CreateTile.WeekdaySat'                          = 'Sáb'
        'CreateTile.WeekdaySun'                          = 'Dom'
        'CreateTile.WeekdayThu'                          = 'Qui'
        'CreateTile.WeekdayTue'                          = 'Ter'
        'CreateTile.WeekdayWed'                          = 'Qua'
        'CreateTile.WorkflowDetailed'                    = 'Detalhado'
        'CreateTile.WorkflowDetailedDescription'         = 'Editar cada campo diretamente'
        'CreateTile.WorkflowEvent'                       = 'Evento'
        'CreateTile.WorkflowEventDescription'            = 'Bloco de tempo no calendário'
        'CreateTile.WorkflowRecurring'                   = 'Recorrente'
        'CreateTile.WorkflowRecurringDescription'        = 'Repetição em um cronograma'
        'CreateTile.WorkflowTask'                        = 'Tarefa'
        'CreateTile.WorkflowTaskDescription'             = 'Trabalho com duração alvo'
    }
}

function Write-Resx {
    param(
        [string]$Path,
        [hashtable]$Map
    )
    $header = @'
<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
'@
    $body = ''
    foreach ($k in ($Map.Keys | Sort-Object)) {
        $v = $Map[$k]
        # XML escape
        $vEsc = $v -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
        $body += "  <data name=`"$k`" xml:space=`"preserve`"><value>$vEsc</value></data>`n"
    }
    $footer = "</root>`n"
    $content = $header + "`n" + $body + $footer
    Set-Content -Path $Path -Value $content -NoNewline -Encoding UTF8
}

$root = "C:\Users\rebui\Desktop\tastile\tastile-desktop\src\TastileDesktop\Resources\Features"
foreach ($lang in @('de', 'fr', 'pt-BR')) {
    $path = "$root\Strings.QuickCreate.$lang.resx"
    Write-Resx -Path $path -Map $translations[$lang]
    Write-Host "Wrote: $path"
}
